### ISSUE TITLE
DomainObjectAllocator should verify the object being allocated is a Domain Object

### ISSUE THREAD

**Issue by jcarvalho** [fenix-framework/fenix-framework#198]
`DomainObjectAllocator` is currently not verifying whether the object being allocated is really a domain object.

If it is not, strange errors may occur.

**Comment by jcarvalho** [comment]
For the JVSTM/OJB backend, this was fixed in ef709d367d68e3d4ef36dba4068339cbb242390c.

**Comment by smmf** [comment]
After commenting on commit ef709d367d68e3d4ef36dba4068339cbb242390c, I just realized that in this thread, a bit higher @jcarvalho mentions that we could check for inheritance from `DomainObject`. I really thing that this is the way to go, as long as there is no need to do a more specific check.

**Comment by jcarvalho** [comment]
(I'll reply here for both the issue and your comment on my commit).

Regarding the specific class within the JVSTM/OJB backend, at the moment, it is the only one that is usable (in fact, ADO and OBDO haven't been merged due to lack of time).

Regarding the usage of the `DomainObject` interface for checking, while it is enough to cover the typical case of a class not being a domain object anymore, it doesn't cover the case in which a non-DO class is inserted on purpose, in order to crash the JVM running it, hence my original proposal of making that check at the `DomainObjectAllocator`, which has access to the concrete backend class in use.

**Comment by smmf** [comment]
> Regarding the specific class within the JVSTM/OJB backend, at the moment, it is the only one that is usable (in fact, ADO and OBDO haven't been merged due to lack of time).

I did not understand the above. Can you explain?  Currently `pt.ist.fenixframework.backend.jvstmojb.pstm.OneBoxDomainObject` **is** a subclass of `pt.ist.fenixframework.core.AbstractDomainObject` (with 2 other classes in between).  I was proposing to use the latter instead of the former. Why do you say it is not possible?

[Sorry, if I did not understand why ADO cannot be used, and you need to explain it further. I haven't been coding on the FF in a while.]

> Regarding the usage of the `DomainObject` interface for checking, while it is enough to cover the typical case of a class not being a domain object anymore, it doesn't cover the case in which a non-DO class is inserted on purpose, in order to crash the JVM running it, hence my original proposal of making that check at the `DomainObjectAllocator`, which has access to the concrete backend class in use.

I don't want to be nitpicking and I'll be happy if OBDO can be replaced with ADO, but your expression is odd. You said: 

> a non-DO class

By definition that means some class that does not implement `DomainObject`, right?  So, such class would fail the new test we're discussing.  How, then, would it crash the VM? I remember [your comment](https://github.com/fenix-framework/fenix-framework/issues/198#issuecomment-65656575), but that's without the test.  Or did you 'abuse' the language, and you meant some class that implements the interface of DO, but is not a subclass of ADO? If that's the case then, again, I would recommend checking with core.ADO as a solution.

**Comment by jcarvalho** [comment]
The stream of comments is getting a bit mess, so I'll explain my reasoning for the change.

In a previous version of the Fenix Framework, `DomainObjectAllocator` was changed, to use a VM-internal API `ReflectionFactory`. This allows us to instantiate an Object X, only invoking the constructor of a superclass (typically, the backend-specific domain object superclass).
This change required `DomainObjectAllocator` to no longer provide a single static method, and instead, receive upon its construction, said backend-specific superclass. So when the `allocateObject` is instantiated, a new object of the given class will be instantiated, using only the constructor of the class passed upon the `DomainObjectAllocator`'s construction.

The issue here, is that if the class given to the `allocateObject` method does not extend that specific backend-specific class, strange errors may occur (I've seen it return null, throw a `NoClassDefFoundError` and even kill the VM with an OS-level error). As such, checking for `DomainObject` (or even `AbstractDomainObject`) would not be enough.

To fully prevent any errors, the `allocateObject` itself should perform this validation. However, since it is on a critical execution path, that check greatly increases the method's complexity and execution time. As such, a compromise was taken: perform that check when loading entries from the `DomainClassInfo`, as that would be the time when all possible classes are loaded into the system.

**Comment by jcarvalho** [comment]
On a sidenote, adding the check to `DomainObjectAllocator` could prevent crashes when it is maliciously used outside the framework, but nothing really prevents a malicious caller from invoking the underlying API directly :)

**Comment by smmf** [comment]
Thanks for taking the time. I had forgotten about the change to `DomainObjectAllocator` to use `ReflectionFactory`. I'm still a bit bothered by the JVSTM/OJB backend doing a specific test with `OBDO`, because, as I initially mentioned, it precludes using other generators in that backend, but I understand the need you have for ensuring that the VM does not crash ;-) Anyway, you might consider opening an issue about the fact that this has been left hardwired?! Either way, I'll close this one.
