### ISSUE TITLE
Support ValueType declaration clashes when ValueType is declared in different dmls

### ISSUE THREAD

**Issue by NunoPinheiro** [fenix-framework/fenix-framework#208]
At the moment, we can't use mutliple dmls if they declare a value type with the same name. 

Although avoiding name clashes is a good feature in non-modular applications, the scope of the value types should be the dml declaring it.

I know that we can use the same "real type" declared as different value types in each dml, but, If I consumed modules from different providers (not created by me), I may not be able to easily change the value type declarations.

**Comment by jcarvalho** [comment]
This topic was discussed in great length when the version 2 of the Fenix Framework was created, and support for modularity was greatly enhanced.

The bottom line was that since the Framework represents Value Types by their name, it would require a major overhaul of the Domain Model API and implementation to change.

The reason that the Domain Model checks for duplicate Value Type declarations is that they can have different externalization definitions.

Consider that you have two modules that declare a Value Type named `Foo`, for a type `com.bar.foo`, and that one decides that it will be externalized as a String, and the other as a `byte[]`. How would the Framework be able to handle this? How would it know which declaration to use? Even worse, is the case where both externalizations are Strings, but with totally different formats!

I know that a possible solution could be to auto-prefix each Value Type declaration, thus avoiding these conflicts. However, this would cause a great burden on anyone who wants to use it.

The discussion for this issue has been a lengthy one, and until now, we haven't found a good tradeoff that allowed us to pull this off. If you have any suggestions regarding this topic, we would be glad to discuss them.

**Comment by jcarvalho** [comment]
Given the issues pointed above and the lack of discussion, I'm closing this, until a better solution can be found.
