### ISSUE TITLE
Inconsistent cache with multiple instances

### ISSUE THREAD

**Issue by Luis-Cruz** [fenix-framework/fenix-framework#214]
There are certain scenarios in which domain objects that have loaded values in a running instance become inconsistent. We have seen this happen specifically with the jvstm-ojb backend. While this may also be an issue with other backeds, this issue will focus on the specific case seen with the jvstm-ojb option.

With two running instances of an application in which both have a domain object loaded in memory up to a certain TX_NUMBER, if one of the application instances is suspended for some reason and the other continues to operate normally, after 3600 seconds the running application assumes that the other instance is no longer running. As a result, it will clear the entry of the suspended instance from FF$LAST_TX_PROCESSED. Consequently updates from the FF$TX_CHANGE_LOGS will be cleared, even though they have not been consumed by the suspended instance.

When the suspended instance returns to normal activity, it will continue to operate even though it's cache contains domain objects that should have been marked with a NOT_LOADED value. In these scenarios, the inconsistencies are produced that in some cases violate application rules.

**Comment by Luis-Cruz** [comment]
When this happens the application that is suspended, should be able to detect that the other instances considered it was no longer active, and should act accordingly, either by invalidating the entire cache or simply exiting (the safer bet).

**Comment by smmf** [comment]
I'd say that is related to how the CleanThread works. Have a look at CleanThread.initializeServerRecord which cleans tx change logs older than 3600s. Even though it is possible to increase that number to a mich larger value (say 1 day), I still think that probably it makes more sense to just kill an app that as been suspended/stopped for such a long time and just restart it.

This problem should not occur in other backends, because their architecture does not depend on keeping any change logs in the persistence store.

**Comment by Luis-Cruz** [comment]
Resolved by https://github.com/fenix-framework/fenix-framework/pull/220
