### ISSUE TITLE
Delete Domain Object : deleted objects can be connected to other objects.

### ISSUE THREAD

**Issue by sergiofbsilva** [fenix-framework/fenix-framework#73]
This problem occurs when a domain object is deleted and then connected to another DO.

The problem can be reproduced with the following steps:
1. git clone git://github.com/fenix-framework/examples.git
2. cd test-delete
3. mvn clean package

The code in this method [testConnectToContactAfterDelete](https://github.com/fenix-framework/examples/blob/master/test-delete/src/main/java/pt/ist/fenixframework/example/helloworld/Main.java#L33) does the following:

1) creates three Person objects, each one in a different tx.
2) erases the first person in a different tx.
3) connect back the first instance to root in a different tx.
4) add a contact and assign it to the Person that has already been deleted.

The test gives the following output:

`Setting the last committed TX number to 0
Transaction number 1
Add person A 
Person A with oid 4294967297 created.
Transaction number 2
Add person B 
Person B with oid 4294967298 created.
Transaction number 3
Add person C 
Person C with oid 4294967299 created.
Transaction number 4
Delete person A
Person A deleted.
Transaction number 5
reset root to person A
Transaction number 6
Add contact testContact to A
Transaction number 7
Show person
    Name: A
    Contact:testContact`

After running this test, the BD becomes inconsistent:

**mysql> select \* from CONTACT;**

| OID | OID_PERSON | PHONE_NUMBER | ID_INTERNAL |
| --- | --- | --- | --- |
| 12884901889 | 4294967297 | testContact | 1 |

**mysql> select \* from PERSON;**

| OID | OID_CONTACT | NAME | OID_APP | ID_INTERNAL |
| --- | --- | --- | --- | --- |
| 4294967298 | NULL | B | 8589934593 | 2 |
| 4294967299 | NULL | C | 8589934593 | 3 |

The Contact 12884901889 is connected to Person 4294967297 but this person is no longer available in the DB.

This problem occurs because deleteDomainObject deletes the object in the DB through DBChanges but still remains in the cache.

Transactions started before the delete transaction must be able to read the deleted objects but subsequent transactions shouldn't be able to read, connect to others or commit deleted objects.

**Comment by legidio** [comment]
@jcarvalho, there is a another case, related I think, of faulty management of deleted DomainObjects that this solution doesn't cover and, IMHO, the Framework should help somehow.

The use case is quite simple:

1. A DomainObject is deleted by means of deleteDomainObject() (i.e., succefully removed from the database after being completely disconnected from other objects)
2. When returning to the presentation tier, the application can somehow obtain the DomainObject's OID from the request and tries to get it with FenixFramework.getDomainObject
3. This method still returns the DomainObject since it hasn't been removed or invalidated in the Framework's cache
4. In order to avoid further usage of the DomainObject, testing for null is not successful since an object is returned by getDomainObject
5. Also, testing that object for is$$do$$Valid() is not an option since it returns true

I understand that this is a problem of the application's Request values management. But in a long hierarchy of Struts' Actions (for e.g.) it is quite easy for a (team of) developer(s, with different FF level of experience) to make such mistakes. 

It is my strong belief that the FenixFramework.getDomainObject method should be more bullet-proof and return null (the Java "standard" for "not available") if an object is invalid for some reason:

a) When is$$do$$valid() = false
b) Like in this particular case, when it was deleted (maybe an upgrade to is$$do$$valid() would suffice?)
c) When the given externalId is invalid (i.e., in most FF backends, for not being a Long)

In a even more radical failsafe strategy, I would very much like to see such method being able to assert that the externalId given was valid in the sense that it actually maps to a given DomainObject class by cross checking it with the method DomainClassInfo.mapOidToClass. As I'm sure you know (from your experience at FenixEdu), this is particularly important when exposing OIDs to an environment outside the application's control (e.g.: public pages that are indexed in search engine bots with OIDs that may no longer exist/be valid ; external webservices that make requests based on OIDs with the same problems ; etc).

In a nutshell, I've been keen on using the following implementation of getDomainObject in some of my code (please be so kind as to look at the end of this comment).

Sorry for the (very) long comment, but these are some thoughts that I've been wanting to share for some time, based on my personal experience with the Fenix Framework. I understand that some points may be difficult to agree to (given the principles that stand as the foundation of the Fenix Framework) or implement across backends, but I really belief that the developer experience with this Framework would be very much improved.

=================================

    public static <T extends DomainObject> T getDomainObject(final String externalId, final Class<T> clazz) {
        T result = null;

        if (isExternalId(externalId, clazz)) {

            final DomainObject domainObject = FenixFramework.getDomainObject(externalId);

            if (domainObject != null && domainObject.is$$do$$Valid()) {
                result = (T) domainObject;
            } else {
                logger.warn("Invalid DomainObject: [ExternalId]=[{}], [Class]=[{}]", externalId, clazz);
            }
        }

        return result;
    }

    public static boolean isExternalId(final String externalId, final Class<? extends DomainObject> clazz) {
        boolean result = false;

        if (isExternalId(externalId) && clazz != null) {
            try {
                result = clazz.isAssignableFrom(DomainClassInfo.mapOidToClass(Long.valueOf(externalId)));
            } catch (final Throwable t) {
                logger.debug(t);
            }
        }

        if (!result) {
            logger.debug("Invalid ExternalId: [String]=[{}], [Class]=[{}]", externalId, clazz);
        }

        return result;
    }

    public static boolean isExternalId(final String externalId) {
        boolean result = false;

        if (StringUtils.isNotBlank(externalId)) {
            try {
                Long.valueOf(externalId);
                result = true;
            } catch (final Throwable t) {
                logger.debug(t);
            }
        }

        return result;
    }

**Comment by smmf** [comment]
@legidio, how does your proposed solution prevent the problem you mention initially, of having the FF.getDomainObject(String) return a cached object?

@jcachopo has, for long, been suggesting a more robust solution where deleted objects are marked as such by setting a known field common to all DOs: e.g. deleted=true.  This has a price to pay, no doubt, but it would "trivially" deal with all cases, including the concurrency aspects of deleting an object while changing it in another transaction.

**Comment by legidio** [comment]
@smmf, I'm sorry, the comment was too long and maybe it became a bit unclear.

The ideia behind the previous code snipet wasn't to propose a full solution to the problem (I think this is something that requires a broader knowledge of all FFs backends other than I have...) but merely to suggest that a possible solution could be to enhance the verifications made by the method FF.getDomainObject(String) so that the returned object is either null or valid.

Example of current usage of FF.getDomainObject when passing an OID of an objected that suffered from the reported problem, i.e., it was deleted. Notice that we have to test for some relation of the object just to make sure that it wasn't deleted...the FF.isDomainObjectValid test is optional, but it actually is recomended if we want to be absolutly certain that the object is available for further computation:

        Registration registration = (Registration) FenixFramework.getDomainObject(getRegistrationOID(request));
        if (registration != null && FenixFramework.isDomainObjectValid(registration) && registration.getDegree() != null) {

            if (registration.getDegree().isSomething()) {
                // something
            }

	    // something else
	}

And now an example of usage with the code snipet of my previous comment. We only have to test the result for null, nothing else. As a bonus, notice that the cast is no longer required, avoiding a very much possible ClassCastException:

        Registration registration = FenixFramework.getDomainObject(getRegistrationOID(request), Registration.class);
        if (registration != null) {

            if (registration.getDegree().isSomething()) {
                // something
            }

	    // something else
	}


Hope I didn't made you all yawn :) Thank you for your time.

**Comment by legidio** [comment]
I forgot to say that (even thought I believe that FF.getDomainObject could be made more bullet-proof) maybe just an enhancement to FF.isDomainObjectValid taking into account the deleted state would already be a great improvement when dealing with DOs.

**Comment by jcarvalho** [comment]
This is a long stream of comments, so I'll try to reply to every point here. Note that all mentions of the Framework's public API only detail the implementation on the JVSTM/OJB backend.

- First, from your post, it seems you are directly using the `is$$do$$Valid()` method. You should **NEVER, EVER** do that. If the method name isn't enough of an hint, you should check the class it's defined in ;)

- Second, `FenixFramework.isDomainObjectValid` does indeed check if the object has been deleted. Just look at the `ClassCastException` being caught [here](https://github.com/fenix-framework/fenix-framework/blob/v2.6.0/backend/jvstm-ojb/runtime/src/main/java/pt/ist/fenixframework/backend/jvstmojb/pstm/OneBoxDomainObject.java#L192) (Deleting an object puts a non-DOState object in the VBox, causing a CCE when trying to access it, which sort of acts as the 'deleted = true' mark that was proposed by @smmf ).

- Third, in the JVSTM/OBJ backend, `FenixFramework.getDomainObject` returns null if the provided value is not syntactically valid (i.e, is not a Long), but it does **NOT** check whether the given object is valid, as it would create too much of a performance penalty in many critical execution paths.

- When interacting with `externalIds` in presentation technology, you should really use a helper method for that. For instance, for Spring, you could use an automated converter ([example](https://github.com/FenixEdu/bennu-spring/blob/v1.2.0/src/main/java/org/fenixedu/bennu/spring/DomainObjectConverter.java#L49)), or in Struts you could add a helper method on a superclass, or a helper class in your project.

- Even if this backend were to be changed to perform `isDomainObjectValid` in every call to `getDomainObject`, the Framework's public API clearly states that: 'If the external identifier is tampered with (in which case a valid DomainObject cannot be found), the result of calling this method is undefined.', so you could not rely on that backend's behavior on your code.

**Comment by jcarvalho** [comment]
Regarding your snippet, in which you check whether the `externalId` of an object is of a valid domain class (by directly checking with the `DomainClassInfo` - which you should never do!), and returning null if it is not.

If this were to be implemented at the Framework level, consider the following scenario: You have a class X, with a 1-many relation with Y. That relation is filled with instances of both Y and subclasses of Y. Now say you delete one of those subclasses. When materializing the relation, the backend would call `getDomainObject`, which would return `null`. This would cause a domain relation to contain a `null` object; which clearly violates the Framework's API.

**Comment by legidio** [comment]
@jcarvalho, thanks for the reply.

- I'm actually using FF.isDomainObjectValid, the code snipet was misleading. Thanks for the heads up.

- I'm sorry, the check on deleted object is in fact implemented. I didn't look carefully to the commit that closed this issue. I know understand what happened: I based my observations on the first implementation of FF.isDomainObjectValid and isValid/is$$do$$Valid methods, which did not have that catch on ClassCastException and the ThisObjectHasBeenDeleted class.

- As for performance issues, I understand your concern. But, IMHO, the tradeoff would be worthwhile. One of the initial ideals of the FF was to allow the developers to be concerned only with business logic and not database technicalities. The current behaviour of getDomainObject is somehow tricky in corner cases that some developers may not have the necessary attention.

- Regarding the scenario of removing from the model a Z class, subclass of Y. On a X-Y* domain relation, what happens currently on such scenario? The FF will materialize an X object containing a set of Y in which some of them are no longer domain objects because they are Z instances? I'm truly asking, I don't know the answer.

I think that this scenario is also of FF responsability, a isDOValid should be called upon on materializing such relations.

Again, I must say I'm not fully aware of all of the FF API and fundamental ideas. These are just my two cents, from the point of view of an FF experienced developer, dealing with developers not so experienced on a daily basis.

Thanks!
